2016-06-18 21:39:00,848 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 21:39:06,762 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 21:40:24,548 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 21:46:23,664 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 21:46:23,674 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:00:02,092 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:00:02,108 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:00:14,828 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:00:24,908 [ERROR] pycurl url reset:(28, 'Connection timed out after 5038 milliseconds')
2016-06-18 22:00:25,134 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:00:26,091 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:03:07,142 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:03:07,144 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:03:56,742 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:03:57,640 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:04:02,927 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:04:03,138 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:04:03,947 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:08:14,068 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:08:19,269 [ERROR] pycurl url reset:(56, 'Recv failure: Connection was aborted')
2016-06-18 22:08:19,269 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:08:19,936 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:10:54,102 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:10:59,191 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:10:59,191 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:11:04,246 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:11:04,247 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:14:03,927 [ERROR] connect database error!(2013, 'Lost connection to MySQL server during query')
2016-06-18 22:14:03,943 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:14:31,036 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:14:31,051 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:14:39,490 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:14:39,490 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:14:41,440 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:14:51,513 [ERROR] pycurl url reset:(28, 'Connection timed out after 5553 milliseconds')
2016-06-18 22:14:51,513 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:16:08,423 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5008 milliseconds')
2016-06-18 22:16:08,423 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:16:13,072 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:16:18,194 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:16:18,194 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:16:51,058 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:16:56,127 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:16:56,127 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:16:56,779 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:18:43,882 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:18:43,882 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:18:49,171 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:18:49,171 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:18:52,585 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:20:14,849 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:20:21,956 [ERROR] pycurl url reset:(28, 'Connection timed out after 5990 milliseconds')
2016-06-18 22:20:22,176 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:20:27,236 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:20:27,486 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:21:15,661 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:21:16,799 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:21:21,858 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:21:22,095 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:21:27,154 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:21:27,387 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:24:40,137 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:24:40,153 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:25:03,127 [DEBUG] Alarm error!'module' object is not callable
2016-06-18 22:25:08,204 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:25:08,204 [DEBUG] Alarm error!'module' object is not callable
2016-06-18 22:25:13,282 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:25:13,282 [DEBUG] Alarm error!'module' object is not callable
2016-06-18 22:26:17,286 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:26:17,302 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:27:39,865 [ERROR] pycurl url reset:(28, 'Connection timed out after 5803 milliseconds')
2016-06-18 22:27:40,799 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:27:44,441 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:27:45,480 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:32:08,256 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:32:08,273 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:32:32,421 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:32:32,436 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:33:23,641 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:33:23,655 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:34:13,686 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:34:13,701 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:34:24,394 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:34:25,279 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:34:30,605 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:34:35,676 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:34:36,128 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:40:03,704 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:40:03,720 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:40:14,530 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:40:15,446 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:40:20,510 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:40:20,934 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:40:27,026 [ERROR] pycurl url reset:(28, 'Connection timed out after 5616 milliseconds')
2016-06-18 22:40:27,255 [DEBUG] Alarm error!function takes exactly 1 argument (3 given)
2016-06-18 22:41:20,553 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:41:26,562 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:41:32,572 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:44:33,697 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:45:19,190 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:45:25,177 [ERROR] pycurl url reset:(28, 'Connection timed out after 5007 milliseconds')
2016-06-18 22:45:30,460 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:47:57,661 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:47:57,661 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:48:22,891 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:48:22,907 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:48:46,880 [ERROR] connect database error!(2003, "Can't connect to MySQL server on '180.76.153.58' (10060)")
2016-06-18 22:48:46,895 [DEBUG] __del__ object error!Runmonitor instance has no attribute 'cursor'
2016-06-18 22:49:05,686 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:49:11,887 [ERROR] pycurl url reset:(28, 'Connection timed out after 5008 milliseconds')
2016-06-18 22:49:20,016 [ERROR] pycurl url reset:(28, 'Connection timed out after 5943 milliseconds')
2016-06-19 10:05:07,026 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5516 milliseconds')
2016-06-20 20:10:11,847 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 69224 out of -1 bytes received')
2016-06-20 20:13:11,440 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 218212 out of -1 bytes received')
2016-06-20 20:44:16,058 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:52:16,054 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:54:12,037 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:54:22,386 [ERROR] pycurl url reset:(28, 'Operation timed out after 10003 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:55:16,873 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 14794 out of -1 bytes received')
2016-06-20 20:55:27,232 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:56:13,330 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 29678 out of -1 bytes received')
2016-06-20 20:57:12,910 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:57:23,275 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:58:17,184 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:59:12,212 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 20:59:22,733 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:01:12,133 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:01:22,463 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:02:13,177 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:03:12,443 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:03:22,805 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:04:15,927 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:05:11,888 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:06:16,043 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:07:18,584 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:08:19,159 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:11:12,503 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:12:12,182 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:13:16,970 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:15:12,587 [ERROR] pycurl url reset:(28, 'Operation timed out after 10004 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:16:19,993 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:18:12,284 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:18:22,663 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:20:11,695 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:20:22,060 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:21:12,338 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:22:12,257 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:23:11,758 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 341548 out of -1 bytes received')
2016-06-20 21:23:23,711 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:23:34,047 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:24:12,235 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:24:22,561 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:26:15,943 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:27:12,162 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:27:22,484 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:28:17,319 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:29:16,554 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:30:12,549 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:31:12,602 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:32:11,837 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:32:22,159 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:33:18,013 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:34:12,006 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:34:22,341 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:35:12,026 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:36:12,551 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:37:12,488 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:38:12,601 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:38:22,964 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:39:12,178 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:41:22,093 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:42:15,434 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:43:12,472 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:43:22,865 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:47:12,562 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:48:11,639 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:48:21,986 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:49:12,026 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:49:22,354 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:51:11,866 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 21:51:22,197 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 22:00:21,755 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 22:10:15,836 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 22:20:15,691 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 0 out of -1 bytes received')
2016-06-20 22:30:11,708 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 23:10:12,615 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 3876 out of -1 bytes received')
2016-06-20 23:10:23,635 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 23:20:11,887 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-20 23:20:22,235 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-20 23:50:12,777 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:00:11,977 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:10:12,669 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:20:11,578 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:20:21,921 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:30:11,901 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:30:22,220 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:40:21,827 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:50:11,882 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 00:50:22,193 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:00:12,156 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:00:23,879 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:10:14,304 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:20:12,345 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:20:22,701 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:30:13,315 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:30:23,664 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:40:11,779 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:40:22,104 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 01:50:12,828 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:10:13,066 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:20:11,965 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:20:22,461 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:30:12,539 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:30:22,867 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:40:12,598 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:40:22,943 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:50:12,689 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 02:50:23,035 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:00:12,169 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:00:22,505 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:10:14,039 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:10:24,438 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:30:12,108 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:40:11,993 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:40:22,321 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:50:12,312 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 03:50:22,889 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 04:00:12,642 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 04:00:22,981 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 04:10:13,062 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 1172 out of -1 bytes received')
2016-06-21 04:10:23,456 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 05:10:21,058 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-21 05:20:20,925 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-21 23:48:07,567 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5517 milliseconds')
2016-06-22 03:42:06,712 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5517 milliseconds')
2016-06-22 04:12:08,588 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5516 milliseconds')
2016-06-22 05:52:11,604 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5515 milliseconds')
2016-06-22 13:58:07,448 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5516 milliseconds')
2016-06-22 17:20:07,300 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5518 milliseconds')
2016-06-22 23:32:07,610 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5515 milliseconds')
2016-06-23 00:38:11,196 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 340551 out of -1 bytes received')
2016-06-23 13:54:11,547 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 282496 out of -1 bytes received')
2016-06-23 17:06:12,124 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-23 17:06:22,427 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 0 out of -1 bytes received')
2016-06-23 17:08:12,416 [ERROR] pycurl url reset:(28, 'Operation timed out after 10002 milliseconds with 0 out of -1 bytes received')
2016-06-23 17:08:22,732 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 3887 out of 90885 bytes received')
2016-06-23 18:34:06,905 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5516 milliseconds')
2016-06-23 21:20:11,440 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 34947 out of -1 bytes received')
2016-06-24 06:52:07,093 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5514 milliseconds')
2016-06-24 09:24:11,654 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 310141 out of -1 bytes received')
2016-06-24 12:34:11,980 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 7924 out of -1 bytes received')
2016-06-25 01:50:11,933 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 218655 out of -1 bytes received')
2016-06-25 06:22:06,681 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5515 milliseconds')
2016-06-25 09:46:11,603 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 135865 out of -1 bytes received')
2016-06-25 13:02:11,640 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 35357 out of -1 bytes received')
2016-06-25 23:44:07,301 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5520 milliseconds')
2016-06-26 05:34:06,709 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5516 milliseconds')
2016-06-26 10:04:11,970 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 374339 out of -1 bytes received')
2016-06-26 11:38:11,330 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 80858 out of -1 bytes received')
2016-06-26 16:00:12,075 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 198789 out of -1 bytes received')
2016-06-26 20:42:11,939 [ERROR] pycurl url reset:(28, 'Operation timed out after 10001 milliseconds with 63779 out of -1 bytes received')
2016-06-26 23:16:11,582 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 132115 out of -1 bytes received')
2016-06-26 23:26:07,004 [ERROR] pycurl url reset:(28, 'Resolving timed out after 5515 milliseconds')
2016-06-27 06:34:11,676 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 309299 out of -1 bytes received')
2016-06-27 08:32:11,943 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 322081 out of -1 bytes received')
2016-06-27 12:02:11,484 [ERROR] pycurl url reset:(28, 'Operation timed out after 10000 milliseconds with 356211 out of -1 bytes received')
